### ISSUE TITLE
asyncio.run() cannot be called from a running event loop on reading file

### ISSUE THREAD

**Issue by Jhsmit** [Jhsmit/awesome-solara#3]
Depending on the implementation of reading out files from either `awesome_solara.components.<file_input / file_input_handler>.FileInput` I get a `RuntimeError`.

Steps to reproduce:
`solara run examples/single_fileinput.py`

Upload a file from the `example_data` directory, type something in the text field and press the 'add' button.

This gives the errors below. I can understand that calling  `asyncio.run()` in the wrong place can give an error, but I don't see exactly why the implementation of `NewItemAsyncIORunTimeError` does give the error while everything works fine is I swap it out with `NewItem` (lines 177-178).

I guess its because when I use `NewItem`, the `on_file` callback gets called in a `hooks.use_thread` context?

In the console:

```
 RuntimeWarning: coroutine 'ClientSideFile.readinto.<locals>.read_all' was never awaited
  self._reader = parsers.TextReader(src, **kwds)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

In the browser:
```
Traceback (most recent call last):
  File "C:\Users\jhsmi\Miniconda3\envs\py39_solara\lib\site-packages\reacton\ipyvue.py", line 23, in handler
    callback_ref.current(*args)
  File "C:\Users\jhsmi\Miniconda3\envs\py39_solara\lib\site-packages\reacton\ipyvuetify.py", line 22, in drop_arguments
    on_click()
  File "C:\Users\jhsmi\pp\awesome-solara\examples\single_fileinput_concat.py", line 141, in on_click
    df = pd.read_csv(file_info[0]["file_obj"])
  File "C:\Users\jhsmi\Miniconda3\envs\py39_solara\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\jhsmi\Miniconda3\envs\py39_solara\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\jhsmi\Miniconda3\envs\py39_solara\lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\jhsmi\Miniconda3\envs\py39_solara\lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\jhsmi\Miniconda3\envs\py39_solara\lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\jhsmi\Miniconda3\envs\py39_solara\lib\site-packages\pandas\io\parsers\readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "C:\Users\jhsmi\Miniconda3\envs\py39_solara\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 547, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 636, in pandas._libs.parsers.TextReader._get_header
  File "pandas\_libs\parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 1965, in pandas._libs.parsers.raise_parser_error
RuntimeError: asyncio.run() cannot be called from a running event loop
```

**Comment by maartenbreddels** [comment]
Good question!

In the case where you read on the button click, your event handler is being called from the solara 'main' thread (the thread your websocket is running on), which already started an ioloop. In the other case, you do the reading from the on_file event handler, which is called from a new thread (since the FileInput is using use_thread).

For instance, this change made it work for me.

```patch
@@ -137,9 +141,12 @@ def NewItemAsyncIORunTimeError(on_add: Callable[[FileInputItem], None]):
         if not file_info:
             return
 
+    def read_df():
         # TODO multiple readers
-        df = pd.read_csv(file_info[0]["file_obj"])
-        set_df(df)
+        if file_info:
+            df = pd.read_csv(file_info[0]["file_obj"])
+            set_df(df)
+    solara.use_thread(read_df, [file_info])
 
```

I have to say, it's quite cumbersome to have the event handler (like on_click) start from a thread.
We run into that issue quite a lot, and I've discussed that with @mariobuikhuizen a while ago, and it would be
nice if we could have some kinda of decorator or hook that will turn an event handler into a event handler that runs in a thread.

**Comment by Jhsmit** [comment]
Suppose I have some kind of big calculation I want to do threaded, which starts when the user presses a button, how would I go about doing that?

**Comment by maartenbreddels** [comment]
Could you say what is missing from the docs/example: 
https://solara.dev/api/use_thread

I can make a guess. I guess it's not obvious you could add a boolean state that would go into the dependencies, and if you also include that in the function that goes the work, e.g. `if not run: return` you can have it perform the work conditionally.

**Comment by Jhsmit** [comment]
Ah yes I think my confusion is from not realizing I can have a boolean who's value is meaningless but is just used as an event. 
Ok I'll give it a try I think i should manage
